// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cov_matern_2
arma::mat cov_matern_2(const arma::mat& X);
RcppExport SEXP _tubeR_cov_matern_2(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cov_matern_2(X));
    return rcpp_result_gen;
END_RCPP
}
// cov_matern_2_cross
arma::mat cov_matern_2_cross(const arma::mat& X, const arma::mat& Z);
RcppExport SEXP _tubeR_cov_matern_2_cross(SEXP XSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(cov_matern_2_cross(X, Z));
    return rcpp_result_gen;
END_RCPP
}
// sqdist_export
arma::mat sqdist_export(const arma::mat& X, const arma::mat& Z);
RcppExport SEXP _tubeR_sqdist_export(SEXP XSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(sqdist_export(X, Z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tubeR_cov_matern_2", (DL_FUNC) &_tubeR_cov_matern_2, 1},
    {"_tubeR_cov_matern_2_cross", (DL_FUNC) &_tubeR_cov_matern_2_cross, 2},
    {"_tubeR_sqdist_export", (DL_FUNC) &_tubeR_sqdist_export, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tubeR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
