# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.matern_2_same <- function(X) {
    .Call(`_tubeR_cov_matern_2`, X)
}

.matern_2_cross <- function(X, Z) {
    .Call(`_tubeR_cov_matern_2_cross`, X, Z)
}

.sqdist <- function(X, Z) {
    .Call(`_tubeR_sqdist_export`, X, Z)
}

